
class DriverConstant:

    DRIVER_TIMEOUT = 60
    ELEMENT_TIMEOUT = 30
    PAGE_LOAD_TIMEOUT = 120
    SHORT_TIMEOUT = 10
    MIDDLE_TIMEOUT = 30
    LONG_TIMEOUT = 60

    CHROME_BROWSER = "chrome"
    FIREFOX_BROWSER = "firefox"
    ANDROID_PLATFORM = "ANDROID"
